export const HEROES_UPDATE_LIST = 'HEROES_UPDATE_LIST'
export const HEROES_UPDATE_SELECTED = 'HEROES_UPDATE_SELECTED'
export const HEROES_IS_FETCHING = 'HEROES_IS_FETCHING'
export const HEROE_UPDATE_DETAIL = 'HEROE_UPDATE_DETAIL' 
